### PR TITLE
Add specs and fix problem of attributes duplications for type string when same value

### PR DESCRIPTION
**Pull request by cbchouinard**
for example when merging : {index: 'cover'} with {index:'cover'} it resulted in {index:'cover cover'}

If added a condition to not duplicate if the string have the same value.

### CODE REVIEW

**Comment by paulyoung** [comment]
Looks good to me.

**Comment by cbchouinard** [comment]
I just added an exclusion array to not merge the key contained in the array when using the helper mergeattributes function.

`$.mergeattributes = (attributes1={},attributes2={},exclusions=[]) ->`

**Comment by paulyoung** [comment]
I'm curious about the motivation for exclusions.

**Comment by paulyoung** [comment]
I think `mergeattributes` should be `mergeAttributes` :camel:

**Comment by cbchouinard** [comment]
@paulyoung I'm using mergeAttributes a lot in the new GOM pipeline and I don't want to include the `attributes.data` in the merged attributes on the leaf tags transform. (related to the memory optimization I'm doing right now)

**Comment by paulyoung** [comment]
@d4tocchini was talking about having different level/layers of transforms which would probably rely on all attributes being persisted until serialization.

**Pull request merged**
